services:
  - type: web
    name: dashboard-saude
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: data
      mountPath: /data
      sizeGB: 1