services:
  - type: web
    name: dashboard-saude
    env: node
    plan: free # ou outro plano, dependendo das suas necessidades
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 # Ajuste conforme necessário